# This is a basic workflow to help you get started with Actions

name: Hugo Build

on:
  push:
    branches: [ new-release ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"


      - name: Load Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.87.0/hugo_0.87.0_Linux-64bit.tar.gz -O hugo.tar.gz
          tar zxvf hugo.tar.gz
          ./hugo build





